#!/bin/bash
cp /usr/lib/libSDL2-2.0.so.0 cmake-build-debug
cp /usr/lib/libSDL2_image-2.0.so.0 cmake-build-debug
cp /usr/lib/libGLEW.so.2.2 cmake-build-debug
cp /usr/lib/libassimp.so.5 cmake-build-debug
cp /usr/lib/libGLX.so.0 cmake-build-debug
cp /usr/lib/libOpenGL.so.0 cmake-build-debug
cp /usr/lib/libstdc++.so.6 cmake-build-debug
cp /usr/lib/libm.so.6 cmake-build-debug
cp /usr/lib/libgcc_s.so.1 cmake-build-debug
cp /usr/lib/libc.so.6 cmake-build-debug
cp /usr/lib/libpng16.so.16 cmake-build-debug
cp /usr/lib/libjxl.so.0.8 cmake-build-debug
cp /usr/lib/libjpeg.so.8 cmake-build-debug
cp /usr/lib/libtiff.so.6 cmake-build-debug
cp /usr/lib/libwebp.so.7 cmake-build-debug
cp /usr/lib/libsharpyuv.so.0 cmake-build-debug
cp /usr/lib/libEGL.so.1 cmake-build-debug
cp /usr/lib/libGL.so.1 cmake-build-debug
cp /usr/lib/libz.so.1 cmake-build-debug
cp /usr/lib/libGLdispatch.so.0 cmake-build-debug
cp /usr/lib/libX11.so.6 cmake-build-debug
cp /usr/lib64/ld-linux-x86-64.so.2 cmake-build-debug
cp /usr/lib/libhwy.so.1 cmake-build-debug
cp /usr/lib/libbrotlidec.so.1 cmake-build-debug
cp /usr/lib/libbrotlienc.so.1 cmake-build-debug
cp /usr/lib/libzstd.so.1 cmake-build-debug
cp /usr/lib/liblzma.so.5 cmake-build-debug
cp /usr/lib/libxcb.so.1 cmake-build-debug
cp /usr/lib/libbrotlicommon.so.1 cmake-build-debug
cp /usr/lib/libXau.so.6 cmake-build-debug
cp /usr/lib/libXdmcp.so.6 cmake-build-debug
